cache:
    directories:
        - $HOME/perl_modules
os: linux
dist: trusty
before_install:
    - bash .travis.bash --cmd before_install
    - eval "$(perl -Mlocal::lib=$HOME/perl_modules)"
    - bash .travis.bash --cmd install
    - cpanm File::Find::Object::Rule IO::All XML::Grammar::Screenplay
    - git clone https://github.com/shlomif/screenplays-common
perl:
    - "5.22"
python:
    - "3.5"
script:
    - bash .travis.bash --cmd build
sudo: required
