=encoding utf8

=head1 Humanity - The Movie

=head2 About

This repository contains the sources for I<Humanity - The Movie>,
an original screenplay by Shlomi Fish (L<http://www.shlomifish.org/>), that
parodies humanity, and particularly modern life.

=head2 Links

=over 4

=item * Homepage

L<http://www.shlomifish.org/humour/humanity/>

=back

=head2 Building

Go to C<humanity/screenplay/> and type C<make> .

=head2 Ideas document / plot summary

The file C<humanity/ideas/ideas.txt> contains some ideas to put into
the story.

=cut

